sudo: false
language: php
dist: trusty

matrix:
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly

  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: nightly

install:
  - composer install

script:
  - ./vendor/bin/phpcs -v
